DUMMYPASS="almafa"
DUMMYTOKEN="d2e63a200f9dd4ba99e9"
PUBLICIP=`ifconfig eth0 | awk '/inet / { print $2 }'`

export SS_OS_KEYSTONE_MYSQL="localhost"
export SS_OS_KEYSTONE_DB="keystone"
export SS_OS_KEYSTONE_DB_USER="keystone"
export SS_OS_KEYSTONE_DB_PASS="$DUMMYPASS"
export SS_OS_KEYSTONE_ADMIN_TOKEN="$DUMMYTOKEN"
export SS_OS_KEYSTONE_ADMIN_USER="admin"
export SS_OS_KEYSTONE_ADMIN_PASS="$DUMMYPASS"
export SS_OS_KEYSTONE_REGION="sciserver"
export SS_OS_KEYSTONE_SERVICE="keystone"
export SS_OS_KEYSTONE_SERVICE_PROJECT="service"
export SS_OS_KEYSTONE_SERVICE_USER="keystone"
export SS_OS_KEYSTONE_SERVICE_PASS="$DUMMYPASS"
export SS_OS_KEYSTONE_ROLE_DEFAULT="_member_"
export SS_OS_KEYSTONE_ROLE_USER="user"
export SS_OS_KEYSTONE_TEST_USER="test"
export SS_OS_KEYSTONE_TEST_PASS="$DUMMYPASS"
export SS_OS_KEYSTONE_SWIFT_USER="swift"
export SS_OS_KEYSTONE_SWIFT_PASS="$DUMMYPASS"

export SS_OS_SWIFT_PROXY_IP=$PUBLICIP
export SS_OS_SWIFT_PROXY_PORT=8081
export SS_OS_SWIFT_ACCOUNT_IP=$PUBLICIP
export SS_OS_SWIFT_ACCOUNT_PORT=6202
export SS_OS_SWIFT_CONTAINER_IP=$PUBLICIP
export SS_OS_SWIFT_CONTAINER_PORT=6201
export SS_OS_SWIFT_OBJECT_IP=$PUBLICIP
export SS_OS_SWIFT_OBJECT_PORT=6200
export SS_OS_SWIFT_DEV=sdb,sdc,sdd

export SS_SCIDRIVE_MYSQL="localhost"
export SS_SCIDRIVE_DB="scidrive"
export SS_SCIDRIVE_USER="scidrive"
export SS_SCIDRIVE_PASS="$DUMMYPASS"

